# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97038f6cfa4fb9447751ab084e55909429fed4795104c9b6cb8f957647fd1266996b3df51a2ae729459dc156e45e3fdc590e0dcdb145bfa735bcf59b554b3feb

test:
  secret_key_base: fa89a86d921cef56a8b0a8ae28a6ce1583a8e617069e86a770adbdceccd248965572960f4d4535073ffc203aac690d612da122dc3a25f1b068d0e192e5c23637

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
